import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import StatsCard from "../components/Cards/StatsCard";
import { SimpleGrid } from "@chakra-ui/react";
import {
  BarChart,
  Bar,
  LineChart,
  Line,
  Cell,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from "recharts";

export default function Home() {
  const data = [
    {
      name: "Jan",
      uv: 4000,
      pv: 2400,
      amt: 2400,
    },
    {
      name: "Feb",
      uv: 3000,
      pv: 1398,
      amt: 2210,
    },
    {
      name: "March",
      uv: 2000,
      pv: 9800,
      amt: 2290,
    },
    {
      name: "April",
      uv: 2780,
      pv: 3908,
      amt: 2000,
    },

    {
      name: "May",
      uv: 2390,
      pv: 3800,
      amt: 2500,
    },
    {
      name: "June",
      uv: 3490,
      pv: 4300,
      amt: 2100,
    },
    {
      name: "July",
      uv: 1890,
      pv: 4800,
      amt: 2181,
    },
  ];
  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SimpleGrid
        justifyContent={"center"}
        spacing={4}
        templateColumns="repeat(auto-fill, minmax(300px, 1fr))"
      >
        <StatsCard label="Most viewed" value="12USD" />
        <StatsCard label="Most viewed" value="12USD" />
        <StatsCard label="Most viewed" value="12USD" />
      </SimpleGrid>
    </div>
  );
}
